logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

# 配置MQ地址
spring:
  rabbitmq:
    host: 192.168.5.214 # 主机名
    port: 5672
    virtual-host: /
    username: itcast
    password: 123321
    listener:
      simple:
        prefetch: 1   # 处理完一条消息后再处理下一条消息